services:
  db:
    image: postgres:11-alpine
    container_name: workout_api_db
    environment:
      POSTGRES_USER: workout
      POSTGRES_PASSWORD: workout
      POSTGRES_DB: workout
    ports:
      - "5432:5432"
    volumes:
      - workout_db_data:/var/lib/postgresql/data

volumes:
  workout_db_data:
